#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2020 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "gruvbox-material"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "slant"
    statusline_iseparator = "fire"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = false

# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto_completion_return_key_behavior = "complete"
auto_completion_tab_key_behavior = "smart"

[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30

[[layers]]
name = 'git'

[[layers]]
name = 'VersionControl'

[[layers]] 
name = "cscope"

[[layers]]
name = "colorscheme"

[[layers]]
name = "gtags"
gtagslabel = "pygments"

[[layers]]
name = "test"

[[layers]]
name = "lang#assembly"

[[layers]]
name = "lang#batch"

[[layers]]
name = "lang#hack"

[[layers]]
name = "lang#groovy"

[[layers]]
name = "lang#graphql"

[[layers]]
name = "lang#ipynb"

[[layers]]
name = "lang#latex"

[[layers]]
name = "lang#lisp"

[[layers]]
name = "lang#markdown"

[[layers]]
name = "lang#matlab"

[[layers]]
name = "lang#powershell"

[[layers]]
name = "lang#r"
repl_command = "R"
enabled_linters = ['rubylint', 'rubocop']
format_on_save = true

[[layers]]
name = "lang#toml"

[[layers]]
name = "lang#tcl"

[[layers]]
name = "lang#vim"

[[layers]]
name = "lang#vue"

[[layers]]
name = "tools#zeal"

[[layers]]
name = "tools#dash"  

[[layers]]
name = 'lang#c'
enable_clang_syntax_highlight = true

[[layers]]
name = "format"

[[layers]]
name = "lang#javascript"

[[layers]]
name = "lang#lua"

 
[[layers]]
name = "lang#asciidoc"

[[layers]]
name = "github"

[[layers]]
name = "ui"

[[layers]]
name = "lang#kotlin"

[[layers]]
name = "lang#typescript"
  
[[layers]]
name = "lang#rust"

[[layers]]
name = 'git'

[[layers]]
  name = 'VersionControl'

[[layers]]
name = "fzf"


[[layers]]
  name = "lang#kotlin"

[[layers]]
  name = "lang#typescript"
  
[[layers]]
  name = "lang#rust"

[[layers]]
  name = "lsp"
  filetypes = [
    "rust",
    "javascript",
    "c",
    "cpp",
    "css",
    "html",
    "objc",
    "objcpp",
    "purescript",
    "ruby",
    "typescript",
    "sh",
    "vue"
  ]

[[layers]]
    name = 'lang#c'
    enable_clang_syntax_highlight = true

[[layers]]
  name = "format"

[[layers]]
  name = "lang#javascript"

[[layers]]
  name = "lang#lua"

[[layers]]
  name = 'lang#python'
  python_interpreter = 'C:\Users\haris\AppData\Local\Programs\Python\Python39\python.exe'
  format_on_save = true

[[layers]]
  name = "lang#java"
  java_formatter_jar = 'C:\google-java-format\google-java-format-1.10.0.jar'

[[layers]]
  name = 'tools#mpv'
  mpv_interpreter = 'C:\Mpv Player\mpv.exe'
  musics_directory = 'D:\HARISH\Music\'

[[layers]]
  name = "ctrlp"

[[layers]]
  name = "chat"

[[layers]]
  name = "debug"

[[layers]]
  name = "ctrlpsapce"


[[layers]]
  name = "fuzzy"

[[layers]]
  name = "games"

[[layers]]  
  name = "denite"

[[layers]]
  name = "lang#dockerfile"

[[layers]]
  name = "lang#go"

[[layers]]
  name = "lang#html"

[[layers]]
  name = "lang#io"

[[layers]]
  name = "lang#json" 

[[layers]]
  name = "nim"

[[layers]]
  name = "nix"

[[layers]]
  name = "lang#sql"

[[layers]]
  name = "lang#xml"
  
[[layers]]
  name = "mail"

[[layers]]
  name = "operator"

[[layers]]
  name = "org"

[[layers]]
  name = "vim"

[[layers]]
  name = "tools"

[[layers]]  
  name = "tools#screensaver"

[[custom_plugins]]
  repo = "tomasr/molokai"
  # note: you need to disable merged feature
  merged = false
 
[[custom_plugins]]
  repo = "sainnhe/gruvbox-material" 
  # note: you need to disable merged feature
  merged = false
 
[[custom_plugins]]
  repo = "ayu-theme/ayu-vim" 
  # note: you need to disable merged feature
  merged = false
  
[[custom_plugins]]
  repo = "ryanoasis/vim-devicons" 
  # note: you need to disable merged feature
  merged = false

[[custom_plugins]]
  repo = "rafi/awesome-vim-colorschemes" 
  # note: you need to disable merged feature
  merged = false
